### ISSUE TITLE
Incompatible with 1.1.0-beta.1

### ISSUE THREAD

**Issue by nniehoff** [nautobot/nautobot-plugin-data-validation-engine#13]
### Environment
* Python version:  3.6.14
* Nautobot version: 1.1.0-beta.1
* nautobot-device-onboarding version:  1.0.0

After installing the plugin and adding it to `PLUGINS` I am unable to start Nautobot:

```no-highlight
Traceback (most recent call last):
  File "/usr/local/bin/nautobot-server", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/nautobot/core/cli.py", line 62, in main
    initializer=_configure_settings,  # Called after defaults
  File "/usr/local/lib/python3.6/site-packages/nautobot/core/runner/runner.py", line 266, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/usr/local/lib/python3.6/site-packages/nautobot/extras/plugins/__init__.py", line 101, in ready
    register_plugin_menu_items(self.verbose_name, menu_items)
  File "/usr/local/lib/python3.6/site-packages/nautobot/extras/plugins/__init__.py", line 380, in register_plugin_menu_items
    registry["nav_menu"]["tabs"]["Plugins"][list(registry["nav_menu"]["tabs"]["Plugins"])[-1]]["weight"]
TypeError: 'set' object is not subscriptable
```
### Steps to Reproduce
1.  Install Nautobot 1.1.0b1
2.  Install data-validation-engine plugin
3.  Enable plugin in nautobot_config PLUGINS
4. start Nautobot

### Expected Behavior

Nautobot Starts

### Observed Behavior

Nautobot Fails to start

**Comment by nniehoff** [comment]
It might also be worth updating `pyproject.toml` to include nautobot as a dependency and limit the versions to < 1.1

**Comment by nniehoff** [comment]
This might be fixed with https://github.com/nautobot/nautobot/pull/662 however that's not part of b1.  I'll close this for now as there are several plugins which seem to be affected.
