### ISSUE TITLE
Running data validation a job fails

### ISSUE THREAD

**Issue by mzbroch** [nautobot/nautobot-plugin-data-validation-engine#71]
### Environment
* Python version:  
* Nautobot version:  2.0 (**next** from 2023-05-31)
* nautobot-data-validation-engine version:  branch `next-2.0`

### Expected Behavior

Job runs successfully

### Observed Behavior

Job fails with a traceback :

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/nautobot/extras/jobs.py", line 1283, in run_job
    output = _run_job()
  File "/usr/local/lib/python3.8/site-packages/nautobot/extras/jobs.py", line 1209, in _run_job
    output = job.run(data=data, commit=commit)
  File "/usr/local/lib/python3.8/site-packages/nautobot_data_validation_engine/jobs.py", line 66, in run
    ins.clean()
  File "/usr/local/lib/python3.8/site-packages/nautobot_data_validation_engine/custom_validators.py", line 226, in clean
    self.compliance_result(message=f"{self.context['object']} is valid")
  File "/usr/local/lib/python3.8/site-packages/nautobot_data_validation_engine/custom_validators.py", line 259, in compliance_result
    result, _ = DataCompliance.objects.update_or_create(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 613, in update_or_create
    obj.save(using=self.db)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 787, in save_base
    post_save.send(
  File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 180, in send
    return [
  File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/usr/local/lib/python3.8/site-packages/nautobot/extras/context_managers.py", line 81, in _curried
    return _curried_func(*args, *moreargs, **{**kwargs, **morekwargs})
  File "/usr/local/lib/python3.8/site-packages/nautobot/extras/signals.py", line 81, in _handle_changed_object
    objectchange = instance.to_objectchange(action)
  File "/usr/local/lib/python3.8/site-packages/nautobot/extras/models/change_logging.py", line 46, in to_objectchange
    object_data_v2=serialize_object_v2(self),
  File "/usr/local/lib/python3.8/site-packages/nautobot/core/models/utils.py", line 142, in serialize_object_v2
    data = serializer_class(obj, context={"request": None}).data
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/fields.py", line 1187, in to_representation
    value = self.enforce_timezone(value)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/fields.py", line 1135, in enforce_timezone
    if timezone.is_aware(value):
  File "/usr/local/lib/python3.8/site-packages/django/utils/timezone.py", line 220, in is_aware
    return value.utcoffset() is not None
AttributeError: 'datetime.date' object has no attribute 'utcoffset'
```

### Steps to Reproduce

1. Create device
2. Create `DataComplianceRule` for device3. 

```
import re
from nautobot_data_validation_engine.custom_validators import DataComplianceRule, ComplianceError, CustomValidatorIterator


class DeviceDataComplianceRules(DataComplianceRule):
    model = "dcim.device"
    enforce = False

    # Checks if a device name contains any special characters other than a dash (-), underscore (_), or period (.) using regex
    def audit_device_name_chars(self):
        if not re.match("^[a-zA-Z0-9\-_.]+$", self.context["object"].name):
            raise ComplianceError({"name": "Device name contains unallowed special characters."})

    # Checks if a device is not assigned to a rack
    def audit_device_rack(self):
        if not self.context["object"].rack:
            raise ComplianceError({"rack": "Device should be assigned to a rack."})

    def audit(self):
        messages = {}
        for fn in [self.audit_device_name_chars, self.audit_device_rack]:
            try:
                fn()
            except ComplianceError as ex:
                messages.update(ex.message_dict)
        if messages:
            raise ComplianceError(messages)


custom_validators = list(CustomValidatorIterator()) + [DeviceDataComplianceRules]
```

4. Execute data compliance job

**Comment by glennmatthews** [comment]
May need a migration in this app to reflect the fact that in 2.0 the `created` field is expected to be a `datetime.datetime`, not a `datetime.date` (nautobot/nautobot#3316)
